services:
  etf-monitor:
    container_name: etf-monitor
    image: deeplakehss/etf-monitor:latest
    restart: unless-stopped
    volumes:
      - ./etfs_to_monitor.yml:/app/etfs_to_monitor.yml:ro
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"